---
title: "Section5"
format: html
---


```{r}
library(tidyverse)
library(readxl)
library(here)
df <- read_excel(here::here("data/slu_graduates_17_23.xlsx"))

## fixes error in the data
df <- df |> mutate(across(everything(),
                          .fns = ~replace(., . ==  "STATS" , "STAT")))
```
```{r}
majors_plot <- 
  df %>% 
  select(-starts_with("minor")) %>%
  pivot_longer(starts_with("major"), names_to = "major_num",
               values_to = "major") %>%
  filter(!is.na(major)) %>%
  group_by(sex, major) %>%
  summarise(n_majors = n()) %>%
  ungroup() %>%
  pivot_wider(names_from = sex, values_from = n_majors) %>%
  mutate(prop_male = M / (`F` + M),
         total_students = `F` + M) %>%
  filter(total_students >= 70) %>%
  mutate(major = fct_reorder(major, prop_male))
```

```{r}
mcss_df <- majors_plot %>% filter(major %in% c("STAT", "MATH", "CS"))
majors_plot %>%
  ggplot(aes(major, prop_male)) +
  geom_point() +
  geom_segment(aes(x = major, xend = major, y = 0, yend = prop_male)) +
  geom_segment(data = mcss_df, aes(x=major,  xend = major, y = 0, yend = prop_male), color = "green") +
  geom_point(data = mcss_df, color = "hotpink") +
  coord_flip() +
  theme_classic() +
  theme(axis.text.x = element_text(size = 13)
  ) +
  labs(caption = "Data source: SLU Instiutional Research Office")

```













